apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "holamicro", "namespace":
      "", "kind": "DeploymentConfig"}]'
  creationTimestamp: null
  labels:
    app: holamicro
    name: holamicro
  name: holamicro-pipeline
spec:
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node {
            stage 'build'
            openshiftBuild(buildConfig: 'holamicro', showBuildLogs: 'true')
            stage 'deploy'
            def toDeploy = input message: 'Do we want to deploy?', parameters: [booleanParam(defaultValue: true, description: '', name: 'to_deploy')]
            if (toDeploy){
                echo 'to deploy'
                openshiftDeploy(deploymentConfig: 'holamicro')
            }else{
                echo 'we wont deploy'
            }
        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
status:
  lastVersion: 0
