apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  generation: 1
  labels:
    app: holamicro
  name: holamicro
spec:
  replicas: 1
  selector:
    app: holamicro
    deploymentconfig: holamicro
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/container.holamicro.image.entrypoint: '["container-entrypoint","/bin/sh","-c","$STI_SCRIPTS_PATH/usage"]'
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: holamicro
        deploymentconfig: holamicro
    spec:
      containers:
      - image: 172.30.140.198:5000/microservices-book/holamicro@sha256:9a9d458a9ea210b40b71f90a3cd705b5e90110557c38b7e50e5e423cc9ad7859
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: api/hola
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: holamicro
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: configprops
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /opt/app-root/src/config
          name: volume-z8608
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: application.properties
            path: application.properties
          name: hola-config
        name: volume-z8608
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - holamicro
      from:
        kind: ImageStreamTag
        name: holamicro:latest
        namespace: microservices-book
    type: ImageChange
  - type: ConfigChange
status: {}
